name: Build CMake Project

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - 'feature/github-actions'

jobs:
  CMake:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        platform:
          - preset: Linux Build
            name: Linux
            extention: ""
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Build Project
        uses: threeal/cmake-action@v2.1.0
        with:
          c-compiler: gcc
          build-dir: build/
          options: |
            BUILD_TESTS=OFF
            BUILD_EXAMPLES=OFF
