name: Build CMake Project

on:
  pull_request:
    branches:
      - develop

jobs:
  CMake:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        platform:
          - preset: Linux Build
            name: Linux
            compiler: "gcc"
          - preset: Windows Build
            name: Windows
            compiler: "x86_64-w64-mingw32-gcc-win32"
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Build Project
        uses: threeal/cmake-action@v2.1.0
        with:
          c-compiler: ${compiler}
          build-dir: ./
          options: |
            BUILD_TESTS=ON
            BUILD_EXAMPLES=OFF
      - name: Test Project
        uses: threeal/ctest-action@v1.1.0
        with:
          test-dir: ./
          verbose: true
