name: Build and Export CMake Project

on:
  push:
    branches:
      - main
      - feature/CrossPlatformBuild
    tags:
      - 'build-**'

jobs:
  CMake:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - preset: Linux Build
            name: Linux
            compiler: "gcc"
          - preset: Windows Build
            name: Windows
            compiler: "gcc-mingw-w64"
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Install WinGW
        run: sudo apt install -y gcc-mingw-w64
      - name: Build Project
        uses: threeal/cmake-action@v2.1.0
        with:
          c-compiler: ${{ matrix.platform.compiler }}
          build-dir: ./
          options: |
            BUILD_TESTS=ON
            BUILD_EXAMPLES=OFF
      - name: Test Project
        uses: threeal/ctest-action@v1.1.0
        with:
          test-dir: ./
          verbose: true
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-${{ matrix.platform.name }}
          path: ./build/
