name: Build CMake Project

on:
  pull_request:
    branches:
      - develop

jobs:
  CMake:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - preset: Linux Build
            name: Linux
            compiler: "gcc"
            compiler_options: ""
            testing: true
          - preset: Windows Build
            name: Windows
            compiler: "x86_64-w64-mingw32-gcc"
            compiler_options: "-pthread"
            testing: false
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Install MinGW
        run: sudo apt install -y gcc-mingw-w64
      - name: Build Project
        uses: threeal/cmake-action@v2.1.0
        env:
            CMAKE_ADDITIONNAL_PLATFORM_OPTION: ${{ matrix.platform.compileroptions }}
        with:
          c-compiler: ${{ matrix.platform.compiler }}
          build-dir: ./
          options: |
            BUILD_TESTS=ON
            BUILD_EXAMPLES=OFF
      - name: Test Project
        uses: threeal/ctest-action@v1.1.0
        if: ${{ matrix.platform.testing }}
        with:
          test-dir: ./
          verbose: true
